### ISSUE TITLE
 Error Fetching Databases

### ISSUE THREAD

**Issue by philipproth** [weareferal/craft-remote-sync#44]
We use Digital Ocean Space and Remote Sync at a production environment and anything works fine. If I install Craft CMS with Nitro + Docker as local environment with the same Digital Ocean Space setting Remote Sync gives me an error "Error Fetching Databases".

**Comment by timmyomahony** [comment]
Interesting. I'll check it out. I haven't tested the plugin with Nitro & Docker. It should be using the PHP SDK to interact with the Digital Ocean Spaces so I wonder why it's failing. Probably network related.

**Comment by timmyomahony** [comment]
Hi @philipproth  I dropped the ball on this issue so apologies 😬. It has been a challenge to manage the plugins alongside client work (not an excuse, just an explanation). I'm getting back on top of everything and have a recent Craft 4 update. Let me know if you stuck with the plugin (and whether this issue got sorted)? 

Nitro has been retired since, but I've been using DDEV myself for local development on projects (and plugin development) and it's working OK, so DDEV might help here.

**Comment by timmyomahony** [comment]
I'm going to close this issue now, but please leave a comment if it's still an issue and I'll re-open and investigate.
