### ISSUE TITLE
Underscore in application name breaks remote sync functionality

### ISSUE THREAD

**Issue by ivanBereznev** [weareferal/craft-remote-sync#45]
Application name is a part of backup file name generated by Remote Sync. And it relies on certain number of underscores in a file name, so if app name contains an underscore and you generate a backup, then Remote Sync fails to list backups:
![broken-remote-sync](https://user-images.githubusercontent.com/18012861/152376885-4c0f6176-958b-43ad-870d-6cb483e67cc0.png)

**Comment by timmyomahony** [comment]
Thanks for reporting @ivanBereznev, I will look into this.

**Comment by timmyomahony** [comment]
Hi @ivanBereznev good news, this should now be fixed in version 4.1.0. I've updated the file format now to use two underscores instead of one, meaning you can have an underscore in the system name.

There are a number of other improvements and fixes in 4.1.0 too, so checkout the release notes:

https://github.com/weareferal/craft-remote-sync/releases/tag/4.1.0

**Comment by ivanBereznev** [comment]
Hi @timmyomahony, perfect, thank you!
